#!/usr/bin/bash
echo $1;
if [ $1 = "os" ]; then
    xrandr --output eDP-1-1 --off;
    xrandr --output HDMI-0 --auto --primary;
elif [ $1 = "of" ]; then
    xrandr --output HDMI-0 --off;
    xrandr --output eDP-1-1 --auto --primary;
elif [ $1 = "both" ]; then
    xrandr --output eDP-1-1 --auto;
    xrandr --output HDMI-0 --auto --primary --right-of eDP-1-1;
fi
