;;; el-easydraw-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from edraw.el

(register-definition-prefixes "edraw" '("edraw-"))


;;; Generated autoloads from edraw-color.el

(register-definition-prefixes "edraw-color" '("edraw-color"))


;;; Generated autoloads from edraw-color-picker.el

(autoload 'edraw-color-picker-insert-color-at "edraw-color-picker" "\
Insert a color selected by color picker at POS-OR-EVENT.

(fn POS-OR-EVENT &optional INITIAL-COLOR OPTIONS)" t)
(autoload 'edraw-color-picker-insert-color "edraw-color-picker" "\
Insert a color selected by color picker at the current point.

Note: Use `edraw-color-picker-insert-color-at' when binding to mouse
events.

(fn &optional INITIAL-COLOR OPTIONS)" t)
(autoload 'edraw-color-picker-replace-or-insert-color-at "edraw-color-picker" "\
Select a color with the color picker. If there is color text at
POS-OR-EVENT, replace it; otherwise, insert the color text.

(fn POS-OR-EVENT &optional OPTIONS)" t)
(autoload 'edraw-color-picker-replace-or-insert-color-at-point "edraw-color-picker" "\
Select a color with the color picker. If there is color text at
the current point, replace it; otherwise, insert the color text.

Note: Use `edraw-color-picker-replace-or-insert-color-at' when binding
to mouse events.

(fn &optional OPTIONS)" t)
(autoload 'edraw-color-picker-replace-color-at "edraw-color-picker" "\
Replace the color at POS-OR-EVENT with the color selected by color picker.

(fn POS-OR-EVENT &optional OPTIONS)" t)
(autoload 'edraw-color-picker-replace-color-at-point "edraw-color-picker" "\
Replace the color at the point with the color selected by color picker.

Note: Use `edraw-color-picker-replace-color-at' when binding to mouse
events.

(fn &optional OPTIONS)" t)
(autoload 'edraw-color-picker-read-color "edraw-color-picker" "\
Read a color from minibuffer or color picker.

(fn &optional PROMPT INITIAL-COLOR ALLOW-STRINGS OPTIONS)" t)
(register-definition-prefixes "edraw-color-picker" '("edraw-color-picker"))


;;; Generated autoloads from edraw-color-picker-mode.el

(autoload 'edraw-color-picker-mode "edraw-color-picker-mode" "\
Toggle color picker support for any buffer.

`edraw-color-picker-mode' is a minor mode that enables replacing or
inserting color text using a color picker in any buffer.

The following keybindings are available in `edraw-color-picker-mode'
\\{edraw-color-picker-mode-map}
The buffer local bindings:
\\{edraw-color-picker-mode--cusmap-buffer-local-keymap}
(you can change the binding by M-x customize-variable
`edraw-color-picker-mode-custom-bindings'

This is a minor mode.  If called interactively, toggle the
`Edraw-Color-Picker mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `edraw-color-picker-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'edraw-color-picker-global-mode 'globalized-minor-mode t)
(defvar edraw-color-picker-global-mode nil "\
Non-nil if Edraw-Color-Picker-Global mode is enabled.
See the `edraw-color-picker-global-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `edraw-color-picker-global-mode'.")
(custom-autoload 'edraw-color-picker-global-mode "edraw-color-picker-mode" nil)
(autoload 'edraw-color-picker-global-mode "edraw-color-picker-mode" "\
Toggle Edraw-Color-Picker mode in all buffers.
With prefix ARG, enable Edraw-Color-Picker-Global mode if ARG is
positive; otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Edraw-Color-Picker mode is enabled in all buffers where
`edraw-color-picker-global-mode--turn-on' would do it.

See `edraw-color-picker-mode' for more information on
Edraw-Color-Picker mode.

(fn &optional ARG)" t)
(register-definition-prefixes "edraw-color-picker-mode" '("edraw-color-picker-"))


;;; Generated autoloads from edraw-dom-svg.el

(register-definition-prefixes "edraw-dom-svg" '("edraw-"))


;;; Generated autoloads from edraw-editor-util.el

(register-definition-prefixes "edraw-editor-util" '("edraw-"))


;;; Generated autoloads from edraw-generator.el

(register-definition-prefixes "edraw-generator" '("edraw-gen-"))


;;; Generated autoloads from edraw-import.el

(autoload 'edraw-convert-file-to-edraw-svg "edraw-import" "\


(fn FILE)")
(autoload 'edraw-convert-buffer-to-edraw-svg-xml "edraw-import" "\


(fn BUFFER OUTPUT)" t)
(autoload 'edraw-import-svg-buffer "edraw-import" "\


(fn BUFFER)")
(autoload 'edraw-import-svg-string "edraw-import" "\


(fn STRING)")
(register-definition-prefixes "edraw-import" '("edraw-"))


;;; Generated autoloads from edraw-math.el

(register-definition-prefixes "edraw-math" '("edraw-"))


;;; Generated autoloads from edraw-mode.el

(autoload 'edraw-mode "edraw-mode" "\
Major mode for editing edraw SVG files.

The following commands are available:

\\{edraw-mode-map}" t)
(autoload 'edraw "edraw-mode" nil t)
(register-definition-prefixes "edraw-mode" '("edraw-mode-"))


;;; Generated autoloads from edraw-msg.el

(register-definition-prefixes "edraw-msg" '("edraw-msg"))


;;; Generated autoloads from edraw-org.el

(register-definition-prefixes "edraw-org" '("edraw-org-"))


;;; Generated autoloads from edraw-org-edit.el

(autoload 'edraw-org-edit-link "edraw-org-edit" "\
Edit the `edraw:' link at point.

_PATH and _ARG are not used. These are passed in when called from
org-link, but since these pieces of information aren't quite
enough, this function parses the link at the current position on
its own.

(fn &optional PATH ARG)" t)
(autoload 'edraw-org-edit-regular-file-link "edraw-org-edit" "\
Edit the `file:' link to the .edraw.svg file at point.

There is a `[[edraw:file=somefile.edraw.svg]]' format for embedding
an external SVG file in an Org document, but if you don't want to
use `edraw:' link type and want to use the regular `file:' link type
([[file:somefile.edraw.svg]] format), this function might help." t)
(autoload 'edraw-org-link-copy-contents-at-point "edraw-org-edit" "\
Copies the contents of the link at point.

Copies all shapes inside the data to the clipboard. Copied shapes
can be pasted in the editor or in the shape picker (custom shape list)." t)
(register-definition-prefixes "edraw-org-edit" '("edraw-org-"))


;;; Generated autoloads from edraw-org-export-html.el

(register-definition-prefixes "edraw-org-export-html" '("edraw-org-"))


;;; Generated autoloads from edraw-org-export-latex.el

(register-definition-prefixes "edraw-org-export-latex" '("edraw-org-export-latex-link"))


;;; Generated autoloads from edraw-org-export-odt.el

(register-definition-prefixes "edraw-org-export-odt" '("edraw-org-export-odt-link"))


;;; Generated autoloads from edraw-path.el

(register-definition-prefixes "edraw-path" '("edraw-"))


;;; Generated autoloads from edraw-property-editor.el

(register-definition-prefixes "edraw-property-editor" '("edraw-"))


;;; Generated autoloads from edraw-shape-picker.el

(register-definition-prefixes "edraw-shape-picker" '("edraw-shape-picker"))


;;; Generated autoloads from edraw-util.el

(register-definition-prefixes "edraw-util" '("edraw-"))


;;; Generated autoloads from edraw-widget.el

(register-definition-prefixes "edraw-widget" '("edraw-widget-"))

;;; End of scraped data

(provide 'el-easydraw-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; el-easydraw-autoloads.el ends here
