;;; org-xournalpp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-xournalpp.el

(autoload 'org-xournalpp-insert-new-image "org-xournalpp" "\
Insert new image with description DESC and path OUTPUT-XOPP-PATH in current buffer.

With a prefix argument the state of org-xournalpp-ask-for-file-name is toggled for this function call.

(fn OUTPUT-XOPP-PATH DESC TEMPLATE)" t)
(autoload 'org-xournalpp-mode "org-xournalpp" "\
Mode for displaying editable xournalpp images within Org file.

This is a minor mode.  If called interactively, toggle the
`Org-Xournalpp mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `org-xournalpp-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "org-xournalpp" '("org-xournalpp-"))

;;; End of scraped data

(provide 'org-xournalpp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-xournalpp-autoloads.el ends here
