;;; sketch-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from sketch-mode.el

(autoload 'sketch "sketch-mode" "\
Initialize or switch to (new) SVG image.
With prefix ARG, create sketch using default (customizable)
values

(fn ARG)" t)
(register-definition-prefixes "sketch-mode" '("list-colors-display" "read-color-web" "show-layers" "sketch-" "svg-"))

;;; End of scraped data

(provide 'sketch-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sketch-mode-autoloads.el ends here
